Added click to mark phases as completed
Nightfirecat/zulrahguide pull request #6
Opened 2019-04-28 10:00 UTC by scv-m

I'm not much of a dev but thought this feature would be handy for myself and others.

2019-04-28 19:06 UTC, Nightfirecat requested changes

2019-04-28 19:06 UTC, Nightfirecat commented on script.js
> +	CLICKABLE_PHASES_SELECTOR = '.phases-completed img',
I'd prefer a new class of `.pattern` be applied to the pattern elements so it's more clear what that class means.

2019-04-28 19:06 UTC, Nightfirecat commented on script.js
> +		event.srcElement.className = (event.srcElement.className == "toggle-completed") ? "" : "toggle-completed";
All of the class checking should be handled using [`Element.classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) (namely `classList#contains()` and `classList#toggle()`), like is being done in `resetToggleCompleted()`.

2019-04-28 19:06 UTC, Nightfirecat commented on script.js
> +}
Add newline at EOF
```suggestion
}

```

2019-04-29 22:30 UTC, scv-m commented on script.js
> +	CLICKABLE_PHASES_SELECTOR = '.phases-completed img',
Do you mean just to rename the class to eg. .pattern-completed?

2019-04-29 22:57 UTC, Nightfirecat commented on script.js
> +	CLICKABLE_PHASES_SELECTOR = '.phases-completed img',
Changing the newly-added class name from `.phases-completed` to `.pattern` is what I mean.

2019-05-08 08:38 UTC, scv-m commented
Pushed the requested changes

2019-05-08 16:32 UTC, Nightfirecat commented
I touched up a couple things and added this in ac37d7dff5a20d520fd95250446aab7c08a42612. Thanks for your contribution!

2019-05-08 16:32 UTC, closed without merging